runtime: python37

instance_class: F2

entrypoint: gunicorn -b :8080 -w 2 main:app

resources:
  memory_gb: 4

inbound_services:
- warmup

automatic_scaling:
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_pending_latency: automatic
  max_concurrent_requests: 50